### ISSUE TITLE
rivacyBefore: '登录即同意',   privacyEnd: '并授权获取本机号码',   checkboxHidden: false,   privacyState: false,   appPrivacyOneName: '《用户协议》',  

### ISSUE THREAD

**Issue by jiangdianlong521** [yoonzm/react-native-ali-onepass#28]
android  正常 
ios checkbox = false  点击登录无反应 checkbox 勾选成功可以正常登录
react-native  0.63.3    
ios iphone 12

**Comment by yoonzm** [comment]
@jiangdianlong521 麻烦看下example能否复现呢
https://github.com/yoonzm/react-native-ali-onepass/blob/master/example/App.js

**Comment by jiangdianlong521** [comment]
@yoonzm  
checkboxHidden: false,
      privacyState: false,
可以复现

**Comment by yoonzm** [comment]
@jiangdianlong521 `checkboxHidden`设置为false则代表需要勾选同意协议后才能登录，逻辑没问题呀

**Comment by jiangdianlong521** [comment]
@yoonzm checkboxHidden = false 点击登录没有任何提示。 android 提示 未同意协议

**Comment by yoonzm** [comment]
@jiangdianlong521 好的，这个我看下能否和安卓保持一致

**Comment by jiangdianlong521** [comment]
@yoonzm 辛苦大佬~大佬yyds

**Comment by Xiaobenchu** [comment]
@yoonzm  相同的问题，iOS不勾选同意协议，tips提示不出现，安卓能够正确的出现，现在有解决问题的方案吗

**Comment by Jeijie** [comment]
我这边可以通过逻辑解决IOS不勾选同意协议没有tips的问题，大家可以参考下：

1. 给自己组件一个变量checked为false，
2. 在监听OnePass.addListener(OnePass.EVENTS.onTokenSuccess里面判断numberCode ===OnePass.RESULT_CODES["700003"]的话就把checked设为!checked
3. 在监听OnePass.addListener(OnePass.EVENTS.onTokenSuccess里面判断
numberCode === OnePass.RESULT_CODES["700002"]的话根据平台是ios和checked是否为true或者false的话来提示tips

**Comment by zhengzhiwu2009** [comment]
> Task :app:mergeExtDexRelease
Execution optimizations have been disabled for task ':app:mergeExtDexRelease' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: 'D:\react_workspace\area-edu-app\android\app\build\intermediates\duplicate_classes_check\release'. Reason: Task ':app:mergeExtDexRelease' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: 'D:\react_workspace\area-edu-app\android\app\build\intermediates\external_file_lib_dex_archives\release'. Reason: Task ':app:mergeExtDexRelease' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :react-native-ali-onepass:bundleReleaseAar FAILED

> Task :app:mergeReleaseJavaResource
Execution optimizations have been disabled for task ':app:mergeReleaseJavaResource' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: 'D:\react_workspace\area-edu-app\android\app\build\intermediates\java_res\release\out'. Reason: Task ':app:mergeReleaseJavaResource' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-ali-onepass:bundleReleaseAar'.
> Error while evaluating property 'hasLocalAarDeps' of task ':react-native-ali-onepass:bundleReleaseAar'
   > Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :react-native-ali-onepass project caused this error: D:\react_workspace\area-edu-app\node_modules\react-native-ali-onepass\android\libs\phoneNumber-L-AuthSDK-2.11.1.aar

**Comment by zhengzhiwu2009** [comment]
window上打包，gradlew assembleRelease，遇到以上问题
